### get tooele tech route
GET http://routes-controllers.onrender.com/ttech HTTP/1.1

### get the root path /
GET http://routes-controllers.onrender.com/ HTTP/1.1

### get all students
GET http://routes-controllers.onrender.com/students HTTP/1.1

### get one student
GET http://routes-controllers.onrender.com/students/64ad791d1708a7bb41971582 HTTP/1.1

### create a student
POST http://routes-controllers.onrender.com/students HTTP/1.1
Content-Type: application/json

{
    "firstName": "Keanu",
    "lastName": "Reeves",
    "email": "johnwick007@killer.com",
    "age": 34,
    "currentCollege": "Assassin's Academy"
}

### update a student
PUT http://routes-controllers.onrender.com/students/64ad791d1708a7bb41971582 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bill",
    "lastName": "Reeves",
    "email": "bowser@killer.com",
    "age": 34,
    "currentCollege": "Assassin's Academy"
}

### delete a student
DELETE http://routes-controllers.onrender.com/students/64ad791d1708a7bb41971582 HTTP/1.1
